
version: 2

models:
  - name: addresses
    description: "address details"
    columns:
      - name: address_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: events
    description: "events"
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: order_items
    description: "items contained in each order"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: orders
    description: "order details"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: products
    description: "product details"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: promos
    description: "promos"
    columns:
      - name: promo_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: users
    description: "user details"
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


